function y = gfsk_Modulator(x,sps)
% GFSK modulator (CPM with Gaussian pulse, BT=0.35, h=1).
persistent mod meanM
if isempty(mod)
  M = 2;
  mod = comm.CPMModulator(...
    'ModulationOrder', M, ...
    'FrequencyPulse', 'Gaussian', ...
    'BandwidthTimeProduct', 0.35, ...
    'ModulationIndex', 1, ...
    'SamplesPerSymbol', sps);
  meanM = mean(0:M-1);
end
y = mod(2*(x-meanM));
end
